### ISSUE TITLE
nvidia-settings 375.20

### ISSUE THREAD

**Issue by brezoi** [Madh93/nvidia-led#2]
Using release 375.20, nvidia-settings segfaults with:

$ nvidia-led no-animation 80
/usr/bin/nvidia-led: line 6:  4277 Aborted                 (core dumped) nvidia-settings -a GPULogoBrightness=$1 > /dev/null 2>&1

Running _nvidia-settings -q all_ doesn't list an attribute named GPULogoBrightness

Just curious if you knew, was looking forward to turning off the lights. Fedora 25, nvidia-settings from negativo17.org

**Comment by Madh93** [comment]
Hi. I've installed `375.20` drivers on Ubuntu 16.04 and it's working fine. It's weird `nvidia-settings -q -all | grep GPULogo` is empty.

What graphic card is?

**Comment by brezoi** [comment]
Seems it's a problem with the nvidia-settings utility bundled with the negativo17.org repo. I built nvidia-settings from source on my machine and it works successfully with your wrapper. Thanks! F25 nvidia-settings that works https://github.com/brezoi/various/blob/master/nvidia-settings
