### ISSUE TITLE
Possible without nvidia-settings?

### ISSUE THREAD

**Issue by vitorp07** [Madh93/nvidia-led#4]
Hi, 
I am running [LibreELEC](https://libreelec.tv/about/) which is a JeOS which includes latest Nvidia drivers and nvidia-xconfig but do not includes nvidia-settings, would it be possible to control the LED without nvidia-settings?
Do you know how nvidia-settings actually implements the LED status changes?
Thank you

**Comment by Madh93** [comment]
Sorry but the LED control is a custom option only offered by `nvidia-settings` utility (at high level at least). I unknow if it's possible modify it at low level :pensive:

**Comment by vitorp07** [comment]
Thank you for responding,
That's what i thought too, now i'm trying to package all the necessary files together and create an addon for Kodi(LibreELEC) to make this work because compiling a LibreELEC build with nvidia-settings alone didn't work.
